"""GRPO (Group Relative Policy Optimisation) training.

Key insight
-----------
GRPO, introduced in DeepSeekMath (2024), eliminates the value function from
PPO by estimating advantages via group-relative normalisation.  For each
prompt, G completions are sampled and scored; the advantage of each completion
is its reward relative to the group mean:

    A_i = (r_i - mean(r_1..r_G)) / std(r_1..r_G)

This "leave-group-out" baseline is similar to RLOO but computed per-group rather
than per-prompt-in-batch, and GRPO applies the PPO clipped ratio loss on top.

Full GRPO objective:
    L_GRPO = -E_i [ min(ratio_i · A_i, clip(ratio_i, 1-ε, 1+ε) · A_i)
                    − β · KL[π_θ || π_ref] ]

where ratio_i = π_θ(y_i|x) / π_old(y_i|x) is the importance weight.

On-policy vs. off-policy
-------------------------
See docs/on_vs_off_policy.md for the detailed treatment.
Short answer: GRPO is ON-POLICY.  Completions are generated by the CURRENT
policy at the START of each training step, then immediately used for the update.
The "old policy" (π_old) is just a snapshot from the start of the same step —
it is not a fixed reference from a previous epoch.

Rollout logging
---------------
This script explicitly logs what GRPO's rollout loop does so you can trace
the gradient flow:

  STEP 1  Generate  : current policy π_θ generates G completions per prompt
  STEP 2  Score     : reward_func(completions) → scalar r per completion
  STEP 3  Advantage : A_i = (r_i − μ) / σ  (group normalise within each prompt)
  STEP 4  Ratio     : π_θ(y_i|x) / π_old(y_i|x)  (importance weight)
  STEP 5  Loss      : −min(ratio·A, clip(ratio, 1−ε, 1+ε)·A) + β·KL
  STEP 6  Update    : gradient step on π_θ

After STEP 6, go to STEP 1 with the UPDATED policy (→ on-policy).

Usage
-----
  python src/train_grpo.py \\
      --prefs_dir data/preferences \\
      --output_dir results/grpo-gpt2 \\
      --sft_model_path ../Week3/fine_tuning_project/results/sft-gpt2 \\
      --max_samples 100

Interview Q&A
-------------
Q: Is GRPO on-policy?
A: Yes, strictly speaking.  At the start of every optimisation step GRPO samples
   G completions from the CURRENT policy parameters π_θ.  These fresh rollouts
   are used immediately for that step's gradient update.  After the update π_θ
   changes, and in the next step entirely new rollouts are generated.
   The "old policy" in the importance-weight ratio is just the policy at the START
   of the same step — not a policy from a previous epoch.  This is contrasted with
   truly off-policy methods like DPO (which uses a fixed preference dataset
   collected from a different policy distribution) or behaviour cloning (SFT).

   Nuance: if ppo_epochs > 1 (multiple gradient steps per rollout batch), then
   later updates within the same epoch ARE technically off-policy relative to
   the very first update.  GRPO clips the importance ratio to handle this safely,
   but purists would call it "near-on-policy" or "mild off-policy."

Q: Why does GRPO not need a value function?
A: The value function in PPO estimates E[future reward] at each token position,
   providing a low-variance baseline.  GRPO replaces this with the mean reward
   across the G sampled completions for the SAME prompt.  Since all G completions
   share the same prompt, their reward mean is a good estimate of V(prompt) with
   zero extra parameters.  The trade-off: you need G ≥ 2 (more memory/compute
   per step) but you avoid the complexity of training a separate value head.
"""

import argparse
import json
import torch
from pathlib import Path

from datasets import Dataset
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import GRPOConfig, GRPOTrainer

# ---------------------------------------------------------------------------
# Chat template (identical to Week 3)
# ---------------------------------------------------------------------------
CHAT_TEMPLATE = (
    "{% for msg in messages %}"
    "{% if msg['role'] == 'user' %}"
    "<|user|>\n{{ msg['content'] }}\n"
    "{% endif %}"
    "{% if msg['role'] == 'assistant' %}"
    "<|assistant|>\n{{ msg['content'] }}{{ eos_token }}"
    "{% endif %}"
    "{% endfor %}"
    "{% if add_generation_prompt %}<|assistant|>\n{% endif %}"
)


# ---------------------------------------------------------------------------
# Reward functions (split into components so SwanLab logs each separately)
#
# TRL logs each function in reward_funcs as its own metric:
#   rewards/reward_format    — is the response grammatically complete?
#   rewards/reward_length    — is the response an appropriate length?
#   rewards/reward_grounding — does the response relate to the prompt?
#
# The combined scalar (0.4·format + 0.3·length + 0.3·grounding) is also
# logged by TRL as rewards/mean across all three functions.
# ---------------------------------------------------------------------------

def reward_format(completions: list[str], **kwargs) -> list[float]:
    """1.0 if completion ends with sentence-final punctuation, else 0.0.

    Scaled to [-0.5, 1.0]: reward = score * 1.5 - 0.5
    (matches the combined reward range so SwanLab axes stay comparable).
    """
    rewards = []
    for comp in completions:
        comp = comp.strip()
        score = 1.0 if comp and comp[-1] in ".!?\"'" else 0.0
        rewards.append(score * 1.5 - 0.5)
    return rewards


def reward_length(completions: list[str], **kwargs) -> list[float]:
    """1.0 if 10 ≤ len(completion) ≤ 200 chars; linearly degrades outside.

    Penalises degenerate (too short) and rambling (too long) outputs.
    Scaled to [-0.5, 1.0].
    """
    rewards = []
    for comp in completions:
        comp = comp.strip()
        n = len(comp)
        if 10 <= n <= 200:
            score = 1.0
        elif n < 10:
            score = n / 10.0
        else:
            score = max(0.0, 1.0 - (n - 200) / 300.0)
        rewards.append(score * 1.5 - 0.5)
    return rewards


def reward_grounding(completions: list[str], prompts: list[str] | None = None, **kwargs) -> list[float]:
    """Fraction of prompt words appearing in completion (weak grounding check).

    Default 0.5 when no prompt is available.
    Scaled to [-0.5, 1.0].
    """
    rewards = []
    for i, comp in enumerate(completions):
        comp = comp.strip()
        score = 0.5
        if prompts is not None and i < len(prompts):
            prompt_words = set(prompts[i].lower().split())
            comp_words = set(comp.lower().split())
            if prompt_words:
                overlap = len(prompt_words & comp_words) / len(prompt_words)
                score = min(1.0, overlap * 3.0)
        rewards.append(score * 1.5 - 0.5)
    return rewards


# ---------------------------------------------------------------------------
# Dataset loader
# ---------------------------------------------------------------------------

def load_prompt_dataset(prefs_dir: Path, split: str = "train") -> Dataset:
    """Load prompts from preference JSONL.

    GRPOTrainer expects a dataset with a "prompt" column.
    """
    path = prefs_dir / f"{split}.jsonl"
    if not path.exists():
        raise FileNotFoundError(
            f"Preference file not found: {path}\n"
            "Run `python data/make_preferences.py` first."
        )
    records = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            records.append({"prompt": rec["prompt"]})
    print(f"  {split:5s} prompts: {len(records):>6,}")
    return Dataset.from_list(records)


# ---------------------------------------------------------------------------
# Rollout logger callback
# ---------------------------------------------------------------------------

from transformers import TrainerCallback


class RolloutLogger(TrainerCallback):
    """Log one example rollout per training step.

    This makes the on-policy generation loop visible during training so you can
    verify: what prompt was used, what the policy generated, what reward was
    assigned, and what advantage the completion received.

    GRPO rollout loop (one step):
      1. Fetch B prompts from the training dataset
      2. Generate G completions per prompt using π_θ (current policy)
      3. Compute rewards r_i for all B×G completions
      4. Group-normalise: A_i = (r_i − μ_group) / (σ_group + ε)
      5. Compute importance ratio: ratio_i = π_θ(y_i|x) / π_old(y_i|x)
      6. Clipped policy gradient update + KL penalty
    """

    def __init__(self, tokenizer, log_every_n_steps: int = 10):
        self.tokenizer = tokenizer
        self.log_every = log_every_n_steps
        self._step = 0

    def on_step_end(self, args, state, control, **kwargs):
        self._step += 1
        if self._step % self.log_every == 0:
            print(
                f"\n[RolloutLogger step={self._step}] "
                f"Policy: π_θ (current checkpoint at step {self._step})\n"
                "  Generation source: CURRENT policy (on-policy)\n"
                "  Advantages: group-relative normalisation within each prompt group\n"
                "  KL: computed against frozen reference (SFT checkpoint)\n"
            )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="GRPO training using TRL GRPOTrainer",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--model_name", default="gpt2")
    parser.add_argument("--sft_model_path",
                        default="../Week3/fine_tuning_project/results/sft-gpt2",
                        help="SFT checkpoint (policy init + KL reference)")
    parser.add_argument("--prefs_dir", default="data/preferences")
    parser.add_argument("--output_dir", default="results/grpo-gpt2")
    parser.add_argument("--max_completion_length", type=int, default=64)
    parser.add_argument("--epochs", type=int, default=1)
    parser.add_argument("--batch_size", type=int, default=2)
    parser.add_argument("--num_generations", type=int, default=2,
                        help="G: completions per prompt for group-relative advantage (≥2, must divide batch_size)")
    parser.add_argument("--kl_coef", type=float, default=0.05,
                        help="KL regularisation coefficient β")
    parser.add_argument("--lr", type=float, default=1e-6)
    parser.add_argument("--max_samples", type=int, default=None)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--log_rollouts_every", type=int, default=10,
                        help="Log rollout diagnostics every N steps")
    parser.add_argument("--swanlab", action="store_true",
                        help="Enable SwanLab logging")
    parser.add_argument("--run_name", default=None,
                        help="SwanLab run name (defaults to output_dir basename)")
    args = parser.parse_args()

    prefs_dir = Path(args.prefs_dir)

    # ── model path ────────────────────────────────────────────────────────────
    model_path = args.sft_model_path
    if not Path(model_path).exists():
        print(f"Warning: SFT checkpoint not found at {model_path}. Using {args.model_name}.")
        model_path = args.model_name

    # ── datasets ──────────────────────────────────────────────────────────────
    print("Loading prompt datasets...")
    train_ds = load_prompt_dataset(prefs_dir, split="train")
    eval_ds  = load_prompt_dataset(prefs_dir, split="eval")

    if args.max_samples:
        train_ds = train_ds.select(range(min(args.max_samples, len(train_ds))))
        eval_ds  = eval_ds.select(range(min(max(1, args.max_samples // 10), len(eval_ds))))

    print(f"Train: {len(train_ds):,}  Eval: {len(eval_ds):,}")

    # ── tokenizer ─────────────────────────────────────────────────────────────
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    tokenizer.chat_template = CHAT_TEMPLATE
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"   # required for batch generation

    # ── truncate prompts to fit within GPT-2's 1024 position limit ────────────
    max_prompt_tokens = 1024 - args.max_completion_length - 4  # 4-token safety margin

    def _truncate(example):
        ids = tokenizer(example["prompt"], add_special_tokens=False,
                        truncation=True, max_length=max_prompt_tokens)["input_ids"]
        example["prompt"] = tokenizer.decode(ids, skip_special_tokens=True)
        return example

    train_ds = train_ds.map(_truncate)
    eval_ds  = eval_ds.map(_truncate)

    # ── GRPO config ───────────────────────────────────────────────────────────
    grpo_config = GRPOConfig(
        output_dir=args.output_dir,
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.batch_size,
        learning_rate=args.lr,
        # GRPO-specific:
        num_generations=args.num_generations,      # G completions per prompt
        max_completion_length=args.max_completion_length,
        beta=args.kl_coef,                         # β: KL regularisation
        model_init_kwargs={"torch_dtype": torch.float32},
        temperature=0.9,
        # Metrics to watch:
        #   rewards/mean   : mean proxy reward
        #   rewards/std    : reward diversity (high = model exploring)
        #   kl             : KL from reference (should stay bounded)
        #   entropy        : policy entropy (should stay positive)
        max_grad_norm=0.5,
        logging_steps=5,
        save_strategy="epoch",
        report_to="none",
        seed=args.seed,
        remove_unused_columns=False,
        bf16=False,
        fp16=False,
    )

    # ── policy model ──────────────────────────────────────────────────────────
    print(f"Loading policy from: {model_path}")
    policy = AutoModelForCausalLM.from_pretrained(model_path, torch_dtype=torch.float32)

    # ── rollout logger + optional SwanLab callbacks ───────────────────────────
    rollout_logger = RolloutLogger(tokenizer, log_every_n_steps=args.log_rollouts_every)
    callbacks = [rollout_logger]
    if args.swanlab:
        from swanlab.integration.transformers import SwanLabCallback
        import swanlab
        run_name = args.run_name or Path(args.output_dir).name
        swanlab.init(project="alignment", experiment_name=run_name,
                     config=vars(args))
        callbacks.append(SwanLabCallback())

    # ── trainer ───────────────────────────────────────────────────────────────
    # Pass all three component functions so TRL logs each separately:
    #   rewards/reward_format / rewards/reward_length / rewards/reward_grounding
    trainer = GRPOTrainer(
        model=policy,
        reward_funcs=[reward_format, reward_length, reward_grounding],
        args=grpo_config,
        train_dataset=train_ds,
        eval_dataset=eval_ds,
        processing_class=tokenizer,
        callbacks=callbacks,
    )

    # ── training ──────────────────────────────────────────────────────────────
    print("\nStarting GRPO training...")
    print(f"  Model          : {model_path}")
    print(f"  Train prompts  : {len(train_ds):,}")
    print(f"  G (gens/prompt): {args.num_generations}  (group size for advantage est.)")
    print(f"  KL coef β      : {args.kl_coef}")
    print()
    print("GRPO rollout loop (per step):")
    print("  1. Generate G completions per prompt  ← CURRENT policy (on-policy)")
    print("  2. Score each completion with reward_func")
    print("  3. Advantage = (r_i − mean) / std   ← group-relative, no value net")
    print("  4. ratio = π_θ(y|x) / π_old(y|x)   ← importance weight")
    print("  5. Clipped loss + β·KL penalty → gradient step")
    print()
    print("Logged metrics (SwanLab):")
    print("  rewards/reward_format    : format score  (ends with punctuation?)")
    print("  rewards/reward_length    : length score  (10–200 chars?)")
    print("  rewards/reward_grounding : grounding score (prompt words in completion?)")
    print("  kl                       : KL divergence to SFT reference")
    print("  entropy                  : policy entropy (watch for mode collapse)")
    print()

    trainer.train()
    trainer.save_model(args.output_dir)
    tokenizer.save_pretrained(args.output_dir)
    print(f"\nSaved GRPO model → {args.output_dir}")


if __name__ == "__main__":
    main()
